# Collect duration
collect_duration: 3600

# Certificate check domains
certificate_domains:
  - www.baidu.com

# Whois check domains
whois_domains:
  - baidu.com

# Resolve domains
resolve_domains:
  - baidu.com

# Request domains
request_domains:
  - host: www.baidu.com
    path: /
    https: true
    domains:
      - www.a.shifen.com
      - www.baidu.com
